name: wbkc-calibration-mc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy==2.3.2
  - scipy==1.16.1
  - pandas==2.3.2
  - pip
  - pip:
      - pytest==8.4.2
      - black==24.10.0
      - ruff==0.6.9
      - pre-commit
