[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wbkc-calibration-mc"
version = "0.1.0"
description = "Whole-body K-40 TBK estimation with Monte Carlo uncertainty."
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Kishor Bhat" }]
requires-python = ">=3.11"
dependencies = [
  "numpy>=1.24",
  "scipy>=1.10",
  "pandas>=2.0",
  "plotly>=5.20",
  "streamlit>=1.30",
  "typing-extensions>=4.7"
]

[project.urls]
Homepage = "https://github.com/kishorbhat-math/wbkc-calibration-mc"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["wbkc"]

[tool.setuptools.package-data]
wbkc = ["py.typed"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E","F","I"]
ignore = ["E501"]