name: CI

on:
  push:
    branches: [ "**" ]
    paths:
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "pyproject.toml"
      - ".github/workflows/**"
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: py${{ matrix.python }} on ${{ matrix.os }}
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Show Python
        run: |
          python -V
          python -c "import sys,platform; print(sys.executable); print(platform.platform())"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . pytest ruff

      - name: Lint
        run: ruff check src tests

      - name: Run tests
        run: python -m pytest -q
